---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: IntelliEyes Market DACH
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '131'
        - 'DACH'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'IntelliEyes::DACH::1st-Lvl'
        - 'IntelliEyes::DACH::2nd-Lvl'
        - 'IntelliEyes::DACH::3rd-Lvl'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM IntelliEyes DACH
  StopAfterMatch: 0
  ValidID: 1
