---
- ChangeBy: admin
  ChangeTime: 2018-06-28 20:53:55
  Comment: ''
  ConfigChange:
    Possible: {}
    PossibleAdd:
      Process:
      - Process-3e624fc75145d4696569f0d54c07cb67
      - Process-f728bbb6b15ea140b77319ee7962c6db
      - Process-dd22d29815efb5c33315c7433049ebdc
  ConfigMatch:
    Properties:
      User:
        Group_rw:
        - digicam
  CreateBy: root@localhost
  CreateTime: 2018-06-27 22:56:48
  Description: Unrelated processes will be hidden.
  ID: '20'
  Name: AAP Digicam Agent Processes
  StopAfterMatch: 0
  ValidID: '1'
