#!/bin/bash

#cd scripts 
#./docker-install
#sudo docker-compose up
#./mail-setup
docker exec -it demootrs_mail_1 /opt/bin/newdomain firma.de 
docker exec -it demootrs_mail_1 /opt/bin/newdomain priv.at 
docker exec -it demootrs_mail_1 /opt/bin/useradd agent@firma.de otrs 
docker exec -it demootrs_mail_1 /opt/bin/useradd support@firma.de otrs
docker exec -it demootrs_mail_1 /opt/bin/useradd kun.de@priv.at otrs
#mkdir mailbox
#mv mailbox
cp -R ../mailbox ./volumes/

#./web-setup
docker exec -it demootrs_otrs_1 sed -i 's/index.pl//' /etc/httpd/conf/httpd.conf
cp ../web/. demootrs_otrs_1:/var/www/html/
docker exec -it demootrs_otrs_1 supervisorctl restart httpd

#./otrs-setup
##
#copy /Kernel/System/Console/Command/Custom
cp -R ../console/Custom ./volumes/config/System/Console/Command/

##
#install additional packages
#curl -o ftp://ftp.otrs.org/pub/otrs/itsm/bundle6/
#ITSM
LATEST=$(curl -s4 ftp://ftp.otrs.org/pub/otrs/itsm/bundle6/ | grep -Eo 'ITSM-[0-9].[0-9].[0-9]+' | tr "[:blank:]" "\n" | sort -V | tail -n 1)
MYWGET="curl -o \"$LATEST.opm\" \"ftp://ftp.otrs.org/pub/otrs/itsm/bundle6/$LATEST.opm\""
docker exec -it demootrs_otrs_1 su - otrs -c "`echo $MYWGET`"
docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Package::Install ./ITSM-*'

#FAQ
LATEST=$(curl -s4 ftp://ftp.otrs.org/pub/otrs/packages/ | grep -Eo 'FAQ-[0-9].[0-9].[0-9]+' | tr "[:blank:]" "\n" | sort -V | tail -n 1)
MYWGET="curl -o \"$LATEST.opm\" \"ftp://ftp.otrs.org/pub/otrs/packages/$LATEST.opm\""
docker exec -it demootrs_otrs_1 su - otrs -c "`echo $MYWGET`"
docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Package::Install ./FAQ-*'

#create faqs !

#create webservices !

#copy config.pm !

##
echo "creating otrs admin "

docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "admin" --first-name OTRS --last-name Admin --email-address "admin@localhost" --password "otrs"'

docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "admin" --user-name "admin" --permission "rw"'
docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "users" --user-name "admin" --permission "rw"'
docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "stats" --user-name "admin" --permission "rw"'
docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "faq" --user-name "admin" --permission "rw"'
docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "faq_admin" --user-name "admin" --permission "rw"'
docker exec -it demootrs_otrs_1 su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "faq_approval" --user-name "admin" --permission "rw"'



#./load config: scenario 1






