#!/bin/bash
echo -n "-> web-setup" 
#sudo docker exec demootrs_otrs  sed -i 's/index.pl//' /etc/httpd/conf/httpd.conf
sudo docker cp ./web/. demootrs_otrs:/var/www/html/ && sudo docker cp ./web/fonts/. demootrs_otrs:/var/www/html/fonts
sudo docker cp ./web/register.pl demootrs_otrs:/opt/otrs/bin/cgi-bin/
sudo docker cp ./web/contact.pl demootrs_otrs:/opt/otrs/bin/cgi-bin/
sudo docker exec demootrs_otrs cp /etc/hosts /tmp/tmp.hosts
sudo docker exec demootrs_otrs sed -i '$ a 127.0.0.1 firma.de' /tmp/tmp.hosts 
sudo docker exec demootrs_otrs sed -i '$ a 127.0.0.1 mail.firma.de' /tmp/tmp.hosts
sudo docker exec demootrs_otrs cp -f /tmp/tmp.hosts /etc/hosts
if grep -q mail.firma.de /etc/hosts; then 
    sudo sed -i '$ a 127.0.0.1    firma.de' /etc/hosts
    sudo sed -i '$ a 127.0.0.1    mail.firma.de' /etc/hosts 
fi
sudo docker cp ./config/apache.conf demootrs_otrs:/etc/httpd/conf.d/firma.conf
echo " ...ok!"
#sudo docker exec demootrs_otrs yum install -y perl-REST-Client
sudo docker exec demootrs_otrs yum install -y yum-utils   device-mapper-persistent-data   lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo docker exec demootrs_otrs yum install -y docker-ce


#check mysqld config at /etc/my.cnf in demootrs_mariadb
if sudo docker exec demootrs_mariadb grep -q max_allowed_packet=20M /etc/my.cnf; then
  sudo docker exec demootrs_mariadb mysql -u root --password="changeme" -e "SET GLOBAL max_allowed_packet=67108864;"
  echo "Warning: MariaDB does not have the required settings for OTRS loaded!"
  echo "set global variable 'max_allowed_packet'"
  sudo docker exec demootrs_mariadb mysql -u otrs --password="changeme" -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
fi
#restart webserver inside container
sudo docker exec demootrs_otrs  supervisorctl restart httpd

echo "-> otrs-setup" 
#copy custom commands, config & scripts
cp -rf ./config/commands/Custom ./volumes/config/System/Console/Command/ #/Kernel/System/Console
mkdir ./volumes/config/scripts/ 
cp -rf ./config/s* ./volumes/config/scripts/
cp -rf ./config/navbar.xml ./volumes/config/scripts/
find ./volumes/config/scripts/. -type f -name '*.sh' | xargs sed -i "s/sudo docker exec demootrs_otrs\s\+su - otrs -c .//g"
find ./volumes/config/scripts/. -type f -name '*.sh' | xargs sed -i 's/'\''$//g'
find ./volumes/config/scripts/. -type f -name '*.sh' | xargs sed -i "s/sudo docker exec demootrs_otrs//g"
if  (grep -q OTRSBusinessRequired ./volumes/config/Output/HTML/Templates/Standard/Header.tt); then
  sudo docker exec demootrs_otrs sed -i '35,38d' /opt/otrs/Kernel/Output/HTML/Templates/Standard/Header.tt
fi

#install additional packages
#FAQ
#LATEST=$(curl -s4 ftp://ftp.otrs.org/pub/otrs/packages/ | grep -Eo 'FAQ-[0-9].[0-9].[0-9]+' | tr "[:blank:]" "\n" | sort -V | tail -n 1)
#if [ ! -f ./volumes/backup/$LATEST.opm ]; then
#  sudo docker exec -it demootrs_otrs curl -o /var/otrs/backups/$LATEST.opm ftp://ftp.otrs.org/pub/otrs/packages/$LATEST.opm
#else 
#echo "File $LATEST.opm already existing."
#fi
sudo cp ./config/FAQ-* ./volumes/backup/
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Package::Install /var/otrs/backups/FAQ-*'

#update faq category & add sub categories
sudo docker exec demootrs_otrs su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Custom::Admin::FAQ::UpdateCategory --name "Readme" --ID "1" --parent "0" --comment "demo-otrs guide" --groups "1,2"'
#add faq articles
sudo docker exec demootrs_otrs su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::FAQ::Import "/opt/otrs/Kernel/System/Console/Command/Custom/Admin/FAQ/intro.csv"'

#Add PostMaster-MailAccount
sudo docker exec demootrs_otrs su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Custom::Admin::MailAccount::Add --login support@firma.de --password otrs --host mail --type IMAP --valid 1 --IMAPFolder INBOX --trusted "1" --dispatchingby Queue --queueID "1" '

#update systemaddress
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Custom::Admin::SystemAddress::Update --valid 1 --ID 1 --name "Mayer GmbH Support" --email-address support@firma.de --queue-name Postmaster'

## add admin
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "admin" --first-name OTRS --last-name Admin --email-address "admin@localhost" --password "otrs"'
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "admin" --user-name "admin" --permission "rw"'
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "users" --user-name "admin" --permission "rw"'
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "stats" --user-name "admin" --permission "rw"'
##faq groups not used anymore, only for otrs 5.x.x or older
#sudo docker exec   demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "faq" --user-name "admin" --permission "rw"'
#sudo docker exec   demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "faq_admin" --user-name "admin" --permission "rw"'
#sudo docker exec   demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "faq_approval" --user-name "admin" --permission "rw"'

#create webservice user
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "webservice" --first-name webservice --last-name user --email-address "root@localhost" --password "otrs"'
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name "users" --user-name "webservice" --permission "rw"'
#create webservices
sudo docker exec demootrs_otrs su - otrs -c '/opt/otrs/bin/otrs.Console.pl Custom::Admin::Webservice::Add --file "GenericTicketConnectorREST.yml" --name "GenericTicketConnectorREST"'
sudo docker exec demootrs_otrs su - otrs -c '/opt/otrs/bin/otrs.Console.pl Custom::Admin::Webservice::Add --file "GenericTicketConnectorSOAP.yml" --name "GenericTicketConnectorSAOP"'

#create new default customer
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::CustomerCompany::Add --name "My Customers" --customer-id "100"'
#create new admin customer user
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::CustomerUser::Add --user-name "testkunde" --first-name Test --last-name Kunde --email-address "testkunde@firma.de" --password "otrs" --customer-id "100"'
sudo docker exec demootrs_otrs  su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Admin::CustomerUser::Add --user-name "webservice" --first-name webservice --last-name customeruser --email-address "root@localhost" --password "otrs" --customer-id "100"'
#connect customer user to group
#sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::CustomerLink --customer-user-login 'kunde1' --group-name 'groupane' --permission 'ro'

#delete  default ticket
sudo docker exec demootrs_otrs su - otrs -c 'perl /opt/otrs/bin/otrs.Console.pl Maint::Ticket::Delete --ticket-id "1"'



#load s1
./config/s1.sh



