---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: IntelliEyes Market BENELUX
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '132'
        - 'BENELUX'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - '132'
        - 'BENELUX'
      User:
        Role:
        - 'IntelliEyesBENELUX'
        - 'IntelliEyesEUROPE'
        - 'IntelliEyesWORLDWIDE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 9
  Name: AAM IntelliEyes BENELUX
  StopAfterMatch: 0
  ValidID: 1
