---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Digicam Market LATAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '114'
        - 'LATAM'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - '114'
        - 'LATAM'
      User:
        Role:
        - 'DigicamLATAM'
        - 'DigicamAMERICA'
        - 'DigicamWORLDWIDE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 11
  Name: AAM Digicam LATAM
  StopAfterMatch: 0
  ValidID: 1
