#!/bin/bash

echo 'Creating Scenario 1'

#create new agent
echo "Creating new agent: " 
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "Mitarbeiter Firma" --first-name Mitar --last-name Beiter --email-address Mitar.Beiter'@firma.org' --password '123'
#Create group & connect to agent
#sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::Add --name 'agents'
#sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name 'agents' --user-name 'Mitarbeiter Firma' --permission 'rw'


#create new customer
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::CustomerCompany::Add --name "Kunden" --customer-id "100"
echo "Creating new customer user: "
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::CustomerUser::Add --user-name "Kunde Konrad" --first-name Kondrad --last-name Kauf --email-address Kondrad.Kauf'@gmx.de' --password '123' --customer-id '100'
#connect customer user to group
#sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::CustomerLink --customer-user-login 'Mitarbeiter Firma' --group-name 'customerX' --permission 'ro,create'
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::CustomerLink --customer-user-login 'kunde1' --group-name 'faq' --permission 'ro'

#create new queue(s)
echo "Creating new queue: "
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Queue::Add --name "Kundenanfragen" --group "agents"



### Change SysConfig Setting with YAML file via command
#Changing CustomerFrontend Module
#perl /opt/otrs/bin/otrs.Console.pl Admin::Config::Read --setting-name CustomerFrontend::Navigation###CustomerTicketOverview###002-Ticket --target-path ./tmp.setting.yml
#perl ./UpdateYAML.pm 
 #     ...
#perl /opt/otrs/bin/otrs.Console.pl Admin::Config::Update --setting-name CustomerFrontend::Navigation###CustomerTicketOverview###002-Ticket --source-path ./tmp.settings.yml
#perl /opt/otrs/bin/otrs.Console.pl Maint::Config::Rebuild

