---
DefaultValue: ''
Link: ''
LinkPreview: ''
PossibleNone: '0'
PossibleValues:  { 
    'Digicam': 'Digicam', 
    'Medoptics': 'Medoptics', 
    'IntelliEyes DACH': 'IntelliEyes DACH', 
    'IntelliEyes CHINA': 'IntelliEyes CHINA'
    }
TranslatableValues: '0'
TreeView: '0'
