---
Activities:
  Activity-02c5fb19033e9a196471a5108ec7c8c2:
    ActivityDialogs:
    - ActivityDialog-d618f797b777e494ca8de8ee997d1e50
    ChangeTime: 2018-03-22 20:33:46
    Config:
      ActivityDialog:
        '1': ActivityDialog-d618f797b777e494ca8de8ee997d1e50
    CreateTime: 2018-03-22 20:33:46
    EntityID: Activity-02c5fb19033e9a196471a5108ec7c8c2
    ID: '7'
    Name: 'Medoptics :: Request for Information'
  Activity-169261b8d7fba5c1c76ac8a47d28532a:
    ActivityDialogs:
    - ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    - ActivityDialog-1d379346f36166a17220f346d7c6f189
    ChangeTime: 2018-03-22 20:36:41
    Config:
      ActivityDialog:
        '1': ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
        '2': ActivityDialog-1d379346f36166a17220f346d7c6f189
    CreateTime: 2018-03-21 16:39:22
    EntityID: Activity-169261b8d7fba5c1c76ac8a47d28532a
    ID: '2'
    Name: ':: Provide Solution (1st-Lvl)'
  Activity-61b2b9d8c601c7e4f3cc6faa53a5233c:
    ActivityDialogs:
    - ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    - ActivityDialog-1d379346f36166a17220f346d7c6f189
    ChangeTime: 2018-03-21 19:17:42
    Config:
      ActivityDialog:
        '1': ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
        '2': ActivityDialog-1d379346f36166a17220f346d7c6f189
    CreateTime: 2018-03-21 18:23:42
    EntityID: Activity-61b2b9d8c601c7e4f3cc6faa53a5233c
    ID: '5'
    Name: ':: Provide Solution (2nd-Lvl)'
  Activity-7f9becb231d6423ff413fde0850fe400:
    ActivityDialogs: []
    ChangeTime: 2018-03-21 16:42:17
    Config: {}
    CreateTime: 2018-03-21 16:42:17
    EntityID: Activity-7f9becb231d6423ff413fde0850fe400
    ID: '3'
    Name: Completed
  Activity-b0b36e2a264e07526abb2aec5e5de254:
    ActivityDialogs:
    - ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    ChangeTime: 2018-03-21 18:24:07
    Config:
      ActivityDialog:
        '1': ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    CreateTime: 2018-03-21 18:24:07
    EntityID: Activity-b0b36e2a264e07526abb2aec5e5de254
    ID: '6'
    Name: ':: Provide Solution (3rd-Lvl)'
ActivityDialogs:
  ActivityDialog-1d379346f36166a17220f346d7c6f189:
    ChangeTime: 2018-03-21 18:23:12
    Config:
      DescriptionLong: ''
      DescriptionShort: Escalate the ticket to the next level.
      FieldOrder:
      - DynamicField_Description
      - DynamicField_Escalate
      Fields:
        DynamicField_Description:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
        DynamicField_Escalate:
          DefaultValue: '1'
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '0'
      Interface:
      - AgentInterface
      Permission: rw
      RequiredLock: '0'
      SubmitAdviceText: ''
      SubmitButtonText: level up
    CreateTime: 2018-03-21 18:23:12
    EntityID: ActivityDialog-1d379346f36166a17220f346d7c6f189
    ID: '6'
    Name: ':: Escalate'
  ActivityDialog-d618f797b777e494ca8de8ee997d1e50:
    ChangeTime: 2018-03-22 20:51:40
    Config:
      DescriptionLong: ''
      DescriptionShort: Please describe your problem.
      FieldOrder:
      - DynamicField_Market
      - Article
      Fields:
        Article:
          Config:
            CommunicationChannel: Internal
            IsVisibleForCustomer: '0'
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
        DynamicField_Market:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '2'
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: 0
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-21 17:56:15
    EntityID: ActivityDialog-d618f797b777e494ca8de8ee997d1e50
    ID: '4'
    Name: 'Medoptics :: Request for Information'
  ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f:
    ChangeTime: 2018-03-21 19:22:57
    Config:
      DescriptionLong: ''
      DescriptionShort: Please describe your solution.
      FieldOrder:
      - State
      - DynamicField_Description
      - DynamicField_Solution
      Fields:
        DynamicField_Description:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '1'
        DynamicField_Solution:
          DefaultValue: '1'
          DescriptionLong: ''
          DescriptionShort: ''
          Display: '0'
        State:
          DefaultValue: ''
          DescriptionLong: ''
          DescriptionShort: completion status
          Display: '2'
      Interface:
      - AgentInterface
      Permission: ''
      RequiredLock: '0'
      SubmitAdviceText: ''
      SubmitButtonText: ''
    CreateTime: 2018-03-21 16:40:52
    EntityID: ActivityDialog-fd2204c0d3197c1af116ae4873f08f6f
    ID: '2'
    Name: ':: Provide Solution'
Process:
  Activities:
  - Activity-02c5fb19033e9a196471a5108ec7c8c2
  - Activity-169261b8d7fba5c1c76ac8a47d28532a
  - Activity-61b2b9d8c601c7e4f3cc6faa53a5233c
  - Activity-7f9becb231d6423ff413fde0850fe400
  - Activity-b0b36e2a264e07526abb2aec5e5de254
  ChangeTime: 2018-03-23 14:38:47
  Config:
    Description: All request without reference to a specific process.
    Path:
      Activity-02c5fb19033e9a196471a5108ec7c8c2:
        Transition-2b1089ad532ca8712045640ce30749ec:
          ActivityEntityID: Activity-169261b8d7fba5c1c76ac8a47d28532a
      Activity-169261b8d7fba5c1c76ac8a47d28532a:
        Transition-b2f2c80df7ed1c01ba0e5185c846cb31:
          ActivityEntityID: Activity-61b2b9d8c601c7e4f3cc6faa53a5233c
        Transition-efce41201952c0c0b5778d1ab13ea1f1:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
      Activity-61b2b9d8c601c7e4f3cc6faa53a5233c:
        Transition-b2f2c80df7ed1c01ba0e5185c846cb31:
          ActivityEntityID: Activity-b0b36e2a264e07526abb2aec5e5de254
        Transition-efce41201952c0c0b5778d1ab13ea1f1:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
      Activity-7f9becb231d6423ff413fde0850fe400: {}
      Activity-b0b36e2a264e07526abb2aec5e5de254:
        Transition-efce41201952c0c0b5778d1ab13ea1f1:
          ActivityEntityID: Activity-7f9becb231d6423ff413fde0850fe400
    StartActivity: Activity-02c5fb19033e9a196471a5108ec7c8c2
    StartActivityDialog: ActivityDialog-d618f797b777e494ca8de8ee997d1e50
  CreateTime: 2018-03-22 20:32:48
  EntityID: Process-a7217d2c38a7737f65255d0e152e3e2b
  ID: '4'
  Layout:
    Activity-02c5fb19033e9a196471a5108ec7c8c2:
      left: '264'
      top: '80.9166870117188'
    Activity-169261b8d7fba5c1c76ac8a47d28532a:
      left: '571'
      top: '85.9166870117188'
    Activity-61b2b9d8c601c7e4f3cc6faa53a5233c:
      left: '663'
      top: '223.916656494141'
    Activity-7f9becb231d6423ff413fde0850fe400:
      left: '1096'
      top: '391'
    Activity-b0b36e2a264e07526abb2aec5e5de254:
      left: '778'
      top: '372.916656494141'
  Name: 'Medoptics :: Request for Information'
  State: Active
  StateEntityID: S1
  TransitionActions: []
  Transitions:
  - Transition-2b1089ad532ca8712045640ce30749ec
  - Transition-b2f2c80df7ed1c01ba0e5185c846cb31
  - Transition-efce41201952c0c0b5778d1ab13ea1f1
  - Transition-b2f2c80df7ed1c01ba0e5185c846cb31
  - Transition-efce41201952c0c0b5778d1ab13ea1f1
  - Transition-efce41201952c0c0b5778d1ab13ea1f1
Transitions:
  Transition-2b1089ad532ca8712045640ce30749ec:
    ChangeTime: 2018-03-21 16:41:57
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_ProcessManagementProcessID:
              Match: ^.
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-21 16:41:57
    EntityID: Transition-2b1089ad532ca8712045640ce30749ec
    ID: '1'
    Name: Always Move
  Transition-b2f2c80df7ed1c01ba0e5185c846cb31:
    ChangeTime: 2018-03-21 19:28:45
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_Escalate:
              Match: '1'
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-21 19:13:30
    EntityID: Transition-b2f2c80df7ed1c01ba0e5185c846cb31
    ID: '2'
    Name: Escalation
  Transition-efce41201952c0c0b5778d1ab13ea1f1:
    ChangeTime: 2018-03-21 19:28:26
    Config:
      Condition:
        '1':
          Fields:
            DynamicField_Solution:
              Match: '1'
              Type: Regexp
          Type: and
      ConditionLinking: and
    CreateTime: 2018-03-21 19:17:18
    EntityID: Transition-efce41201952c0c0b5778d1ab13ea1f1
    ID: '3'
    Name: Solution
