---
Process:
  Activities: []
  ChangeTime: 2018-03-22 21:26:32
  Config:
    Description: Request a new service
    Path: {}
    StartActivity: ''
    StartActivityDialog: ''
  CreateTime: 2018-03-22 21:25:54
  EntityID: Process-58ad44a52828e35ef1883e5d553094b7
  ID: '10'
  Layout: {}
  Name: 'IntelliEyes :: New Service'
  State: Inactive
  StateEntityID: S2
  TransitionActions: []
  Transitions: []
