---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market AMERICA
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '107'
        - 'AMERICA'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'Agent::1stLvl::AMERICA'
        - 'Agent::2ndLvl::AMERICA'
        - 'Agent::3rdLvl::AMERICA'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 9
  Name: AAM Agent AMERICA
  StopAfterMatch: 0
  ValidID: 1
