---
DefaultValue: ''
Link: ''
LinkPreview: ''
PossibleNone: '0'
PossibleValues:  { 
    'Digicam Customer': 'Digicam Customer', 
    'Medoptics Private': 'Medoptics Private', 
    'Medoptics DACH': 'Medoptics DACH', 
    'Medoptics BENELUX': 'Medoptics Benelux', 
    'Medoptics NAM': 'Medoptics North America', 
    'Medoptics LATAM': 'Medoptics Latin America',
    'IntelliEyes DACH': 'IntelliEyes DACH', 
    'IntelliEyes NAM': 'IntelliEyes NAM'
    }
TranslatableValues: '0'
TreeView: '0'
