#!/bin/bash

docker exec -it mail-server /opt/bin/newdomain firma.de 
docker exec -it mail-server /opt/bin/newdomain priv.at 
docker exec -it mail-server /opt/bin/useradd agent@firma.de otrs 
docker exec -it mail-server /opt/bin/useradd support@firma.de otrs
docker exec -it mail-server /opt/bin/useradd kun.de@priv.at otrs
#mkdir mailbox
#mv mailbox
cp -R ../mailbox ./volumes/
