#!/bin/bash

sudo apt-get install -y -q libapache2-mod-perl2 libdbd-mysql-perl libtimedate-perl libnet-dns-perl libnet-ldap-perl \
    libio-socket-ssl-perl libpdf-api2-perl libdbd-mysql-perl libsoap-lite-perl libtext-csv-xs-perl \
    libjson-xs-perl libapache-dbi-perl libxml-libxml-perl libxml-libxslt-perl libyaml-perl \
    libarchive-zip-perl libcrypt-eksblowfish-perl libencode-hanextra-perl libmail-imapclient-perl \
    libtemplate-perl

#sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
#sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
#sudo apt-get -y -q install mysql-server
if [ -d /opt/otrs ]; then
		echo "[ ok ] otrs directory already exists"
else
		echo "[ add ] creating /opt/otrs"
#		wget http://ftp.otrs.org/pub/otrs/otrs-latest.tar.gz
		wget http://ftp.otrs.org/pub/otrs/otrs-5.0.26.tar.gz	
		tar xzf otrs-*.tar
		mv otrs-* /opt/otrs
fi

if grep -q "otrs" /etc/group
	then
			echo "[ ok ] otrs user already exists"
	else
			echo "[ add ] creating otrs user"
			sudo useradd -d /opt/otrs -c 'OTRSUser' otrs
			sudo usermod -G www otrs
	fi
sudo cp /opt/otrs/Kernel/Config.pm.dist /opt/otrs/Kernel/Config.pm
perl -cw /opt/otrs/bin/cgi-bin/index.pl
perl -cw /opt/otrs/bin/cgi-bin/customer.pl
perl -cw /opt/otrs/bin/cgi-bin/Console.pl
sudo apt-get install -y -q qapache2 libapache2-mod-perl2
sudo ln -s /opt/otrs/scripts/apache2-httpd.include.conf /etc/apache2/sites-enabled/zzz_otrs.conf
a2enmod perl
a2enmod version
a2enmod deflate
a2enmod filter
a2enmod headers
#sudo /opt/otrs/bin/otrs.SetPermissions.pl
#sudo touch /etc/my.cnf 
#sudo echo -e '[mysqld] \nmax_allowed_packet = 64M \nquery_cache_size = 32M \ninnodb_log_file_size = 256M' > /etc/my.cnf
cd /opt/otrs
#mysql -u root -proot -e 'create database otrs charset utf8'
#mysql -u root -proot otrs < scripts/database/otrs-schema.mysql.sql
#mysql -u root -proot otrs < scripts/database/otrs-initial_insert.mysql.sql
#mysql -u root -proot otrs < scripts/database/otrs-schema-post.mysql.sql
#mysql -u root -proot -e 'GRANT ALL PRIVILEGES ON otrs.* TO otrs@localhost IDENTIFIED BY "some-pass" WITH GRANT OPTION;'
#mysql -u root -p -e 'FLUSH PRIVILEGES;'
#sudo -u postgres psql -q -c "CREATE DATABASE otrs OWNER otrs ENCODING 'utf8';"
#sudo -u otrs 	  psql -q -d otrs -f "/opt/otrs/scripts/database/otrs-schema.postgresql.sql"
#sudo -u otrs 	  psql -q -d otrs -f "/opt/otrs/scripts/database/otrs-initial_insert.postgresql.sql"
#sudo -u otrs 	  psql -q -d otrs -f "/opt/otrs/scripts/database/otrs-schema-post.postgresql.sql"

#sudo ./otrsadmin
#sudo ./otrsconfig



