#!/bin/bash


##Connect to mail server
#   Admin -> PostMaster Mail Accounts -> add mail account
#   SysConfig -> Core & Core::SendMail
##

##Change/Set System Mail Address
#   Admin -> Email Addresses
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Dev::Code::Generate::ConsoleCommand Admin::SystemAddress::Update
sudo -u otrs mv ConsoleCommand/SystemAddress/Update.pm /opt/otrs/Kernel/System/Console/Command/Admin/SystemAddress
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::SystemAddress::Update --ID=1 --email-address=otrs@localhost3 --valid=2 --name='OTRS system' --queue-name=Raw

##

##Create admin account
echo "creating otrs admin "

sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "admin1" --first-name OTRS --last-name Admin --email-address admin'@itslab.local' --password 'otrs'
#set admin group permissions
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name 'admin' --user-name 'admin' --permission 'rw'
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name 'users' --user-name 'admin' --permission 'rw'
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name 'stats' --user-name 'admin' --permission 'rw'
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name 'faq' --user-name 'admin' --permission 'rw'
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name 'faq_admin' --user-name 'admin' --permission 'rw'
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::UserLink --group-name 'faq_approval' --user-name 'admin' --permission 'rw'
##

##Create groups
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::Add --name "DispatcherTeam"
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Role::Add --name "Produkt1Team"
##

##Add Agent1 (DispatcherFrau1)
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "dispatcher1" --first-name OTRS --last-name Admin --email-address dispatcher1'@itslab.local' --password 'otrs'
##

##Add Agent1 (Produkt1Entwickler1)
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "produkt1entwickler1" --first-name OTRS --last-name Admin --email-address produkt1entwickler1'@itslab.local' --password 'otrs'
##

##Add Agent2 (Produkt1Entwickler2)
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::User::Add --user-name "produkt1entwickler2" --first-name OTRS --last-name Admin --email-address produkt1entwickler2'@itslab.local' --password 'otrs'
##

##Create agent roles
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Role::Add --name "DispatcherRole"
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Role::Add --name "Produkt1EntwicklerRole"
#link role to groups
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Group::RoleLink --group-name "DispatcherTeam" --role-name "DispatcherRole" --permission "create" --permission "ro"

#link agents to role
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Role::UserLink --user-name "dispatcher1" --role-name "DispatcherRole"
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Role::UserLink --user-name "produkt1entwickler1" --role-name "Produkt1EntwicklerRole"
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Role::UserLink --user-name "produkt1entwickler2" --role-name "Produkt1EntwicklerRole"
##


##Create queue
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Queue::Add --name "DispatcherQueue" --group "DispatcherTeam"
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::Queue::Add --name "Produkt1Queue" --group "Produkt1Team"
##

##Add Customer
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::CustomerCompany::Add --name "Kunde1 GmbH" --customer-id "kunde1id"
##
##Add CustomerUser
sudo -u otrs perl /opt/otrs/bin/otrs.Console.pl Admin::CustomerUser::Add --user-name "kunde1mitarbeiter1" --first-name Kondrad --last-name Kauf --email-address kunde'@itslab.local' --password '123' --customer-id 'kunde1id'
##






