#!/bin/bash

echo "hello user";
perl /opt/otrs/bin/otrs.Console.pl Help Admin::User::Add;

echo 'Adding users for Scenario 2'
echo "Creating new agents: "

declare -a Username
declare -a Firstname
declare -a Lastname

Username[1]="Mitarbeiter Hotline";Firstname[1]=Hans;Lastname[1]=Peter,
Username[2]='Mitarbeiter Sales';Firstname[2]=Jürgen;Lastname[2]=Kunert
Username[3]='Mitarbeiter Logistik';Firstname[3]=Gustav;Lastname[3]=Müller;

for i in "${!Username[@]}"
do

	echo --user-name ${Username[$i]} --first-name ${Firstname[$i]} --last-name ${Lastname[$i]} --email-address "${Firstname[$i]}.${Lastname[$i]}@firma.org" --password '123'

done



