---
- AccessKey: m
  Block: ''
  Description: Tickets.
  Group: []
  GroupRo: []
  Link: Action=CustomerTicketOverview;Subaction=MyTickets
  LinkOption: ''
  Name: Tickets
  NavBar: Ticket
  Prio: '100'
  Type: Menu
- AccessKey: ''
  Block: ''
  Description: My Tickets.
  Group: []
  GroupRo: []
  Link: Action=CustomerTicketOverview;Subaction=MyTickets
  LinkOption: ''
  Name: My Tickets
  NavBar: Ticket
  Prio: '110'
  Type: Submenu
- AccessKey: t
  Block: ''
  Description: Company Tickets.
  Group: []
  GroupRo: []
  Link: Action=CustomerTicketOverview;Subaction=CompanyTickets
  LinkOption: ''
  Name: Company Tickets
  NavBar: none
  Prio: '120'
  Type: Submenu

