#!/bin/bash
##
#Create Webservices

#REST connector
#http://localhost/otrs/nph-genericinterface.pl/Webservice/<webservice>/<operation>
#http://localhost/otrs/nph-genericinterface.pl/Webservice/Test/Resource 
