---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Medoptics Market NAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '123'
        - 'NAM'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - '123'
        - 'NAM'
      User:
        Role:
        - 'MedopticsNAM'
        - 'MedopticsAMERICA'
        - 'MedopticsWORLDWIDE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 10
  Name: AAM Medoptics NAM
  StopAfterMatch: 0
  ValidID: 1
