---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Digicam Market NAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '113'
        - 'NAM'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - '113'
        - 'NAM'
      User:
        Role:
        - 'DigicamNAM'
        - 'DigicamAMERICA'
        - 'DigicamWORLDWIDE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 10
  Name: AAM Digicam NAM
  StopAfterMatch: 0
  ValidID: 1
