---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: IntelliEyes Market BENELUX
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '132'
        - 'BENELUX'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'IntelliEyes::CHINA::1st-Lvl'
        - 'IntelliEyes::CHINA::2nd-Lvl'
        - 'IntelliEyes::CHINA::3rd-Lvl'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 9
  Name: AAM Agent IntelliEyes BENELUX
  StopAfterMatch: 0
  ValidID: 1
