---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: IntelliEyes Market NAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '133'
        - 'NAM'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - '133'
        - 'NAM'
      User:
        Role:
        - 'IntelliEyesNAM'
        - 'IntelliEyesAMERICA'
        - 'IntelliEyesWORLDWIDE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 10
  Name: AAM IntelliEyes NAM
  StopAfterMatch: 0
  ValidID: 1
