---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Digicam Market DACH
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '111'
        - 'DACH'
  ConfigMatch:
    Properties:
      CustomerUser:
        UserCustomerID:
        - '111'
        - 'DACH'
      User:
        Role:
        - 'DigicamDACH'
        - 'DigicamEUROPE'
        - 'DigicamWORLDWIDE'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 8
  Name: AAM Digicam DACH
  StopAfterMatch: 0
  ValidID: 1
