---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market NAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '104'
        - 'NAM'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'Agent::1stLvl::NAM'
        - 'Agent::2ndLvl::NAM'
        - 'Agent::3rdLvl::NAM'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 10
  Name: AAM Agent NAM
  StopAfterMatch: 0
  ValidID: 1
