---
- ChangeBy: admin
  ChangeTime: 2018-03-14 11:27:21
  Comment: Market LATAM
  ConfigChange:
    PossibleAdd:
      Ticket:
        DynamicField_Market:
        - '105'
        - 'LATAM'
  ConfigMatch:
    Properties:
      User:
        Role:
        - 'Agent::1stLvl::LATAM'
        - 'Agent::2ndLvl::LATAM'
        - 'Agent::3rdLvl::LATAM'
  CreateBy: admin
  CreateTime: 2018-03-14 11:27:21
  Description: Unrelated Markets will be hidden.
  ID: 11
  Name: AAM Agent LATAM
  StopAfterMatch: 0
  ValidID: 1
